### ISSUE TITLE
Could not resolve all dependencies

### ISSUE THREAD

**Issue by samblake** [sbuettner/spring-boot-autoconfigure-wro4j#2]
When running `gradle build` I get:

> Could not resolve all dependencies for configuration ':compile'.
> > Could not find de.infinit:spring-boot-autoconfigure-wro4j:LATEST_VERSION.

My gradle.build looks like:

> buildscript {
>      repositories {
>            mavenCentral() 
>      }
>      dependencies {
>            classpath "org.springframework.boot:spring-boot-gradle-plugin:1.2.1.RELEASE"
>            classpath "com.sourcemuse.gradle.plugin:gradle-mongo-plugin:0.2.0"
>      }
> }
> 
> allprojects {
>      apply plugin: 'java'
>      apply plugin: 'eclipse'
>      apply plugin: 'spring-boot'
>      apply plugin: 'mongo'
>      apply plugin: 'groovy'
> 
> ```
>  sourceCompatibility = 1.8
> 
>  repositories {
>        mavenCentral()
>        jcenter()
>        maven { url 'http://dl.bintray.com/sbuettner/maven' }
>  }
> ```
> 
> }
> 
> task wrapper(type: Wrapper) {
>      gradleVersion = '1.12'
> }
> 
> dependencies { 
>      compile "org.springframework.boot:spring-boot-starter-web"
>      compile "org.springframework.boot:spring-boot-starter-undertow"
>      compile "org.springframework.boot:spring-boot-starter-actuator"
>      compile "org.springframework.boot:spring-boot-starter-data-mongodb"
>      compile "org.springframework.boot:spring-boot-starter-velocity"
> 
> ```
>  compile "de.infinit:spring-boot-autoconfigure-wro4j:LATEST_VERSION"
> ```
> 
> }

**Comment by sbuettner** [comment]
`LATEST_VERSION` is just a placeholder for the latest version.

Have a look at the repository at https://bintray.com/sbuettner/maven/spring-boot-autoconfigure-wro4j/view

Cheers

**Comment by samblake** [comment]
I'd already tried putting 0.0.6 in there, I get the same issue.
