### ISSUE TITLE
Library should be available via JCenter

### ISSUE THREAD

**Issue by holgerstolzenberg** [sbuettner/spring-boot-autoconfigure-wro4j#5]
As you are already publishing your released artifacts to Bintray, this should an easy thing to do. Currently every developer who wants to use your lib needs to declare your Bintray repo somewhere (in the build, company maven proxy,...).

You can sync your library to JCenter which has production degree stability, even if you decide to move away from Bintray someday.

Instruction on how to do the sync can be found here:
https://bintray.com/docs/usermanual/uploads/uploads_includingyourpackagesinjcenter.html

**Comment by dsyer** [comment]
+1. Also if you want more people to use it, it would be a good idea to get it in Maven Central (you can do that from Bintray as well).
